// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://weturogomzotiocwyymj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndldHVyb2dvbXpvdGlvY3d5eW1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MjUyNjEsImV4cCI6MjA2NzMwMTI2MX0.aPlH7TGTNE-6m7N87_K7zmycTBeGoam0nmfzPkEtl58";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});